# Generated by Django 3.2.25 on 2025-02-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250128_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
