# Generated by Django 3.2.25 on 2025-02-09 21:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='main_image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.property_image_file_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available for Rent', 'for_rent'), ('Available for Purchase', 'for_sale'), ('Rented Out', 'rented_out'), ('Sold', 'sold')], default='for_sale', max_length=50),
        ),
    ]
